name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install Puppeteer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libasound2 libpango1.0-0 libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0

    - name: Install dependencies
      run: npm install

    - name: Run Puppeteer tests
      run: npm test

    - name: Build Docker image
      run: docker build -t mzeinedine/ds-midterm-image:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.mzeinedine }}
        password: ${{ secrets.dckr_pat_YKXjGQDjwedBk8JMkbFAB5AnO88 }}

    - name: Push Docker image to Docker Hub
      run: docker push mzeinedine/ds-midterm-image:latest
